# Generated by Django 5.2.8 on 2025-11-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluida', 'Concluída'), ('atrasada', 'Atrasada')], max_length=20),
        ),
    ]
